package com.example.antennapodplugin;

import android.app.Service;
import android.content.Intent;
import android.os.IBinder;
import android.os.ParcelFileDescriptor;
import android.util.Log;
import androidx.annotation.Nullable;

import de.danoeh.antennapod.plugin.host.IMediaProcessorPlugin;
import de.danoeh.antennapod.plugin.host.PluginContract;
import de.danoeh.antennapod.plugin.host.PluginMediaRequest;
import de.danoeh.antennapod.plugin.host.PluginMediaResult;

public class TranscriptionPluginService extends Service {
    private static final String TAG = "TranscriptionPlugin";
    private static final String PLUGIN_ID = "sample-transcription";

    private final IMediaProcessorPlugin.Stub binder = new IMediaProcessorPlugin.Stub() {
        @Override
        public String getPluginId() {
            return PLUGIN_ID;
        }

        @Override
        public int getCapabilities() {
            return PluginContract.CAPABILITY_TRANSCRIPTION;
        }

        @Override
        public PluginMediaResult process(PluginMediaRequest request) {
            PluginMediaResult result = new PluginMediaResult();
            try {
                String transcript = transcribe(request);
                result.setSuccess(true);
                result.setResultType(PluginContract.RESULT_TYPE_TRANSCRIPT);
                result.setContentMimeType("text/vtt");
                result.setContent(transcript);
            } catch (Exception e) {
                Log.e(TAG, "Transcription failed", e);
                result.setSuccess(false);
                result.setMessage(e.getMessage());
            }
            return result;
        }
    };

    private String transcribe(PluginMediaRequest request) throws Exception {
        ParcelFileDescriptor fd = request.getMediaFd();
        long sizeBytes = fd != null ? fd.getStatSize() : 0;
        Log.d(TAG, "Transcribing '" + request.getEpisodeTitle() + "' (" + sizeBytes + " bytes)");
        // Replace this placeholder with a real speech-to-text engine that reads
        // the audio from request.getMediaFd() and returns WebVTT/SRT/JSON text.
        return "WEBVTT\n\n00:00:00.000 --> 00:00:05.000\n"
                + "[Generated by the sample AntennaPod transcription plugin]\n";
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return binder;
    }
}
